version: '3'
services:
  sample:
    image: self-net-copy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      test_network:

networks:
  test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 50.0.0.0/24